shfmt to 2 spaces consistently

diff --git a/bin/iree-link-python-bindings b/bin/iree-link-python-bindings
--- a/bin/iree-link-python-bindings
+++ b/bin/iree-link-python-bindings
@@ -3,20 +3,20 @@
 set -euo pipefail
 
 if [[ -z $VIRTUAL_ENV ]]; then
-    echo "Not in a virtual environment, refusing to run"
-    exit 1
+  echo "Not in a virtual environment, refusing to run"
+  exit 1
 fi
 
 declare build_dir
 if [[ -x "$PWD/tools/iree-opt" ]]; then
-    build_dir="$PWD"
+  build_dir="$PWD"
 elif [[ -f "${PWD:h}/build/tools/iree-opt" ]]; then
-    build_dir="${PWD:h}/build"
+  build_dir="${PWD:h}/build"
 elif [[ -f "$PWD/build/tools-iree-opt" ]]; then
-    build_dir="$PWD/build"
+  build_dir="$PWD/build"
 else
-    echo "Can't find a built IREE"
-    exit 1
+  echo "Can't find a built IREE"
+  exit 1
 fi
 
 cd "$build_dir"
diff --git a/bin/iree-setup-environment b/bin/iree-setup-environment
--- a/bin/iree-setup-environment
+++ b/bin/iree-setup-environment
@@ -3,31 +3,31 @@
 set -euo pipefail
 
 if [[ $# -lt 1 ]]; then
-   echo "Usage: $0 [root directory]"
-   exit 1
+  echo "Usage: $0 [root directory]"
+  exit 1
 fi
 
 root_dir="$1"
 if [[ ! -d "$root_dir/src/compiler" ]]; then
-    echo "Error: expected $root_dir to heuristically be an IREE checkout"
-    exit 1
+  echo "Error: expected $root_dir to heuristically be an IREE checkout"
+  exit 1
 fi
 
 pushd "$root_dir"
-if [[ ! -a "$root_dir/.envrc" ]]; then
-    echo "use iree $root_dir $root_dir/build python3 $root_dir/src" >.envrc
-    direnv allow .
+if [[ ! -e "$root_dir/.envrc" ]]; then
+  echo "use iree $root_dir $root_dir/build python3 $root_dir/src" >.envrc
+  direnv allow .
 fi
 eval "$(direnv export zsh)"
 echo "Installing Python dependencies..."
 uv pip install -q -r "$root_dir/src/runtime/bindings/python/iree/runtime/build_requirements.txt"
 uv pip install -q nanobind pre-commit
 
-if [[ ! -a "$root_dir/compile_commands.json" ]]; then
-    ln -s "$root_dir/build/compile_commands.json" "compile_commands.json"
+if [[ ! -e "$root_dir/compile_commands.json" ]]; then
+  ln -s "$root_dir/build/compile_commands.json" "compile_commands.json"
 fi
-if [[ ! -a "$root_dir/tablegen_compile_commands.yml" ]]; then
-    ln -s "$root_dir/build/tablegen_compile_commands.yml" "tablegen_compile_commands.yml"
+if [[ ! -e "$root_dir/tablegen_compile_commands.yml" ]]; then
+  ln -s "$root_dir/build/tablegen_compile_commands.yml" "tablegen_compile_commands.yml"
 fi
 
 echo "Set up IREE build envoronment in $root_dir"
diff --git a/bin/llvm-setup-environment b/bin/llvm-setup-environment
--- a/bin/llvm-setup-environment
+++ b/bin/llvm-setup-environment
@@ -3,32 +3,32 @@
 set -euo pipefail
 
 if [[ $# -lt 1 ]]; then
-   echo "Usage: $0 [root directory]"
-   exit 1
+  echo "Usage: $0 [root directory]"
+  exit 1
 fi
 
 root_dir="$1"
 if [[ ! -d "$root_dir/src/mlir" ]]; then
-    echo "Error: expected $root_dir to heuristically be an LLVM checkout"
-    exit 1
+  echo "Error: expected $root_dir to heuristically be an LLVM checkout"
+  exit 1
 fi
 
 pushd "$root_dir"
-if [[ ! -a "$root_dir/.envrc" ]]; then
-    echo "layout uv" >.envrc
-    echo "PATH_add $root_dir/build/bin" >>.envrc
-    direnv allow .
+if [[ ! -e "$root_dir/.envrc" ]]; then
+  echo "layout uv" >.envrc
+  echo "PATH_add $root_dir/build/bin" >>.envrc
+  direnv allow .
 fi
 eval "$(direnv export zsh)"
 echo "Installing Python dependencies..."
 uv pip install -q -r "$root_dir/src/mlir/python/requirements.txt"
 uv pip install -q pygments # LLVM needs this
 
-if [[ ! -a "$root_dir/compile_commands.json" ]]; then
-    ln -s "$root_dir/build/compile_commands.json" "compile_commands.json"
+if [[ ! -e "$root_dir/compile_commands.json" ]]; then
+  ln -s "$root_dir/build/compile_commands.json" "compile_commands.json"
 fi
-if [[ ! -a "$root_dir/tablegen_compile_commands.yml" ]]; then
-    ln -s "$root_dir/build/tablegen_compile_commands.yml" "tablegen_compile_commands.yml"
+if [[ ! -e "$root_dir/tablegen_compile_commands.yml" ]]; then
+  ln -s "$root_dir/build/tablegen_compile_commands.yml" "tablegen_compile_commands.yml"
 fi
 
 echo "Set up LLVM build environment in $root_dir"
